language: erlang
sudo: false
otp_release:
    - 18.1
before_script:
    - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3
script:
    - ./rebar3 compile
    - ./rebar3 dialyzer
    - ./rebar3 xref
    - ./rebar3 eunit
    - ./rebar3 edoc
